__title__ = 'concurrent-log-handler'
__description__ = 'RotatingFileHandler replacement with concurrency, gzip and Windows support'
__url__ = 'https://github.com/Preston-Landers/concurrent-log-handler'
__version__ = '0.9.20'
__author__ = 'Preston Landers'
__author_email__ = 'planders@utexas.edu'
__license__ = 'http://www.apache.org/licenses/LICENSE-2.0'
__copyright__ = 'Copyright 2021 Preston Landers'
